In [48]:
# importing libraries to be used in this exercise

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
import warnings 
warnings.filterwarnings('ignore')

pd.set_option('max_columns', None)
%matplotlib inline

In [2]:
data = pd.read_csv('/storage/emulated/0/Hamoye/StageB/energydata_complete.csv')

In [3]:
data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,55.20,7.026667,84.256667,17.200000,41.626667,18.2,48.900000,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,55.20,6.833333,84.063333,17.200000,41.560000,18.2,48.863333,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,55.09,6.560000,83.156667,17.200000,41.433333,18.2,48.730000,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,55.09,6.433333,83.423333,17.133333,41.290000,18.1,48.590000,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,55.09,6.366667,84.893333,17.200000,41.230000,18.1,48.590000,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

Data Exploration

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [5]:
data.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,19.592106,50.949283,7.910939,54.609083,20.267106,35.388200,22.029107,42.936165,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,1.844623,9.022034,6.090347,31.149806,2.109993,5.114208,1.956162,5.224361,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,15.330000,29.815000,-6.065000,1.000000,15.390000,23.200000,16.306667,29.600000,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,18.277500,45.400000,3.626667,30.025000,18.700000,31.500000,20.790000,39.066667,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,19.390000,49.090000,7.300000,55.290000,20.033333,34.863333,22.100000,42.375000,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,20.619643,53.663333,11.256000,83.226667,21.600000,39.000000,23.390000,46.536000,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,25.795000,96.321667,28.290000,99.900000,26.000000,51.400000,27.230000,58.780000,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

#### Dropping the `lights` and `date` columns.

In [6]:
data.drop(['lights', 'date'], axis=1, inplace=True)

In [7]:
data

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,55.200000,7.026667,84.256667,17.200000,41.626667,18.2000,48.900000,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,55.200000,6.833333,84.063333,17.200000,41.560000,18.2000,48.863333,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,55.090000,6.560000,83.156667,17.200000,41.433333,18.2000,48.730000,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
3,50,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,55.090000,6.433333,83.423333,17.133333,41.290000,18.1000,48.590000,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,55.090000,6.366667,84.893333,17.200000,41.230000,18.1000,48.590000,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,52.400000,24.796667,1.000000,24.500000,44.500000,24.7000,50.074000,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,90,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,52.326667,24.196667,1.000000,24.557143,44.414286,24.7000,49.790000,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,52.266667,23.626667,1.000000,24.540000,44.400000,24.7000,49.660000,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,52.200000,22.433333,1.000000,24.500000,44.295714,24.6625,49.518750,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,52.200000,21.026667,1.000000,24.500000,44.054000,24.7360,49.736000,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

# Separating the columns into similar groups to facilitate intuition

In [8]:
col_temp = ["T1","T2","T3","T4","T5","T6","T7","T8","T9"]

col_hum = ["RH_1","RH_2","RH_3","RH_4","RH_5","RH_6","RH_7","RH_8","RH_9"]


col_weather = ["T_out", "Tdewpoint","RH_out","Press_mm_hg",
                "Windspeed","Visibility"] 

col_random = ['rv1', 'rv2']

col_target = 'Appliances'

## Normalizing the features in the dataset using MinMaxScaler

In [9]:
scaler = MinMaxScaler()

normed_data = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
normed_data

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,T6,RH_6,T7,RH_7,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.327350,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,0.381070,0.841827,0.170594,0.653428,0.173329,0.661412,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.327350,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,0.375443,0.839872,0.170594,0.651064,0.173329,0.660155,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.327350,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,0.367487,0.830704,0.170594,0.646572,0.173329,0.655586,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.327350,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,0.363800,0.833401,0.164310,0.641489,0.164175,0.650788,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.327350,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,0.361859,0.848264,0.170594,0.639362,0.164175,0.650788,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,0.084112,0.926786,0.537657,0.711655,0.606309,0.830841,0.579374,0.864865,0.765258,0.752031,0.339590,0.898317,0.000000,0.858624,0.755319,0.768386,0.701645,0.864724,0.729443,0.891747,0.602326,0.416667,0.238095,0.348718,0.901961,0.861981,0.861981
19731,0.074766,0.919747,0.536006,0.701769,0.607836,0.825302,0.582178,0.864865,0.765258,0.754897,0.338487,0.880852,0.000000,0.864010,0.752280,0.768386,0.691912,0.864724,0.729443,0.887460,0.602326,0.421053,0.250000,0.361538,0.900452,0.985726,0.985726
19732,0.242991,0.919747,0.538666,0.692651,0.627198,0.818378,0.603988,0.864865,0.771233,0.754897,0.337585,0.864260,0.000000,0.862394,0.751773,0.768386,0.687457,0.864724,0.729443,0.883173,0.602326,0.425439,0.261905,0.374359,0.898944,0.583979,0.583979
19733,0.383178,0.919747,0.549491,0.677054,0.634717,0.805085,0.585294,0.864865,0.773794,0.752031,0.336583,0.829525,0.000000,0.858624,0.748075,0.764953,0.682617,0.864724,0.730581,0.878885,0.602326,0.429825,0.273810,0.387179,0.897436,0.126371,0.126371
19734,0.392523,0.919747,0.538758,0.666171,0.632902,0.799546,0.579062,0.864865,0.781192,0.752031,0.336583,0.788580,0.000000,0.858624,0.739504,0.771681,0.690062,0.864724,0.731719,0.874598,0.602326,0.434211,0.285714,0.400000,0.895928,0.682391,0.682391

## Separate dependent and independent variables

In [40]:
feature_vars = normed_data.drop(columns=['rv1', 'rv2', 'Appliances'])
target_var = normed_data[col_target]

## Split dataset into train and test set

In [11]:
x_train, x_test, y_train, y_test = train_test_split(feature_vars, target_var, train_size=0.7, random_state=42)

In [42]:
lr = LinearRegression()
lr.fit(x_train, y_train)

# predicting the output of the training set
# using the Linear Regression model
y_train_predict = lr.predict(x_train)

# predicting the output of the test set
# using the Linear Regression model
y_test_predict = lr.predict(x_test)

test_mse = mean_squared_error(y_test, y_test_predict)

# calculate root mean squared value

test_rmse = np.sqrt(test_mse)

print(test_rmse)

0.08749885665797491

# Question 1

A best fit line relating X and Y has a R-Squared value of 0.75. How do I interpret this information?

**My Answer: The model is performing with 75% accuracy**

# Question 2

Train a lasso regression model with an alpha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights?

### Solution:

In [13]:
# instantiating Lasso
lasso = Lasso(alpha=0.001)

# fitting the training data
lasso.fit(x_train, y_train)


# create a pandas series with the coefficients as the values
# using the column names of x_train as the index
weights = pd.Series(lasso.coef_, x_train.columns)

# use boolean indexing to return values
# that are NOT equal to zero
weights = weights[weights != 0]

# print the length of the returned value
print('Features with non-zero weights:', len(weights))

Features with non-zero weights: 4

# Question 3

The Lasso can be interpreted as least-squares linear regression where:

**My Answer: Weights are regularized with the L1 norm**

# Question 4

Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

**Solution:**

In [14]:
# instantiating linear regression
lr = LinearRegression()

# fitting the training data
lr.fit(x_train, y_train)



# create a pandas series with the coefficients as the values
# using the column names of x_train as the index
weights = pd.Series(lr.coef_, x_train.columns)

# sorting the values in the pandas series
weights = weights.sort_values()

# since weights have been sorted, the feature
# with the lowest value will be the first
# while that with the highest value will
# be the last

weights


# from the output, this is equivalent to RH_2 and RH_1 respectively8

RH_2          -0.456587
T_out         -0.321718
T2            -0.236055
T9            -0.189866
RH_8          -0.157577
RH_out        -0.077563
RH_7          -0.044565
RH_9          -0.039879
T5            -0.015725
T1            -0.003342
Press_mm_hg    0.006853
T7             0.010370
Visibility     0.012289
RH_5           0.015944
RH_4           0.026430
T4             0.029065
Windspeed      0.029192
RH_6           0.038092
RH_3           0.095988
T8             0.101944
Tdewpoint      0.117641
T6             0.236368
T3             0.290571
RH_1           0.553501
dtype: float64

# Question 5

In the different terms of the bias-variance tradeoff, which of the following is substantially more harmful to the test error than the training error?

**My Answer: Variance**

# Question 6

What is the Residual Sum of Squares (in two decimal places)?

**Solution:**

In [43]:
# residual sum of squares is calculated as follows

rss = np.sum(np.square(y_test - y_test_predict))
print ('Residual sum of squares:', round(rss, 2))

Residual sum of squares: 45.33

# Question 7

How many coefficients do you need to estimate a simple linear regression model (One independent variable)?

**My Answer: 1**

# Question 8

What is the Coefficient of Determination (in two decimal places)?

**Solution**

In [17]:
# from the linear regression model, the coefficient
# of determination can be calculated by finding the r-squared value
print ('Coefficient of determination:', round(r2_score(y_test, y_test_predict), 2))

Coefficient of determination: 0.15

# Question 9

In linear regression, L2 regularization is equivalent to imposing a:

**My Answer: Gaussian prior**

# Question 10

What is the Mean Absolute Error (in two decimal places)?

**Solution**

In [18]:
test_mae = mean_absolute_error(y_test, y_test_predict)

print('Mean absolute error:', round(test_mae, 2))

Mean absolute error: 0.05

# Question 11

What is the new RMSE with the Lasso Regression (in 3 decimal places)? 

**Solution:**

In [19]:
# instantiating lasso regression
lasso = Lasso(alpha=0.001)

# fitting the train data
lasso.fit(x_train, y_train)

# predicting values for y_test with the regression
y_test_predict_lasso = lasso.predict(x_test)

# calculating the mean squared error
test_mse_lasso = mean_squared_error(y_test, y_test_predict_lasso)

# calculating the root mean squared error
lasso_rmse = np.sqrt(test_mse_lasso)
print('Root mean squared error for Lasso Regression:', round(lasso_rmse, 3))

Root mean squared error for Lasso Regression: 0.094

# Question 12

Which of these is not an assumption of Linear Regression?

**My Answer: Heteroscedasticity**

# Question 13

Train a ridge regression model with an alpha value of 0.4. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

**Solution:**

In [39]:
# instantiating Ridge regression
ridge = Ridge(alpha=0.5)

# fitting the train data
ridge.fit(x_train, y_train)

y_test_predict_ridge = ridge.predict(x_test)

# calculating the mean squared error
test_mse_ridge = mean_squared_error(y_test, y_test_predict_ridge)

# calculating the root mean squared error
ridge_rmse = np.sqrt(test_mse_ridge)

print('Root mean squared error for Ridge Regression:', ridge_rmse, '\n')

# print the rmse value for test set on Linear Regression
print ('Test root mean squared value:', test_rmse)

Root mean squared error for Ridge Regression: 0.0875263915407331

Test root mean squared value: 0.08749885665797491

**Comparing both values from the output above shows that there is NO change.**

# Question 14

What can you use to find the best fit line for data in Linear Regression?

**My Answer: None of the above**

There is **Least Squared Error** in the option but I only know it as **Least Squared Method**. Thought the *Error* might have been included intentionally, hence why I chose None.

# Question 15

Adding more basis functions in a linear model:

**Answer: Decrease Model Bias**

# Question 16

Cross validation:

**Answer: None of the above**

# Question 17

What is the Root Mean Squared Error (in three decimal places)?

**Solution:**

In [44]:
lr = LinearRegression()
lr.fit(x_train, y_train)

# predicting the output of the training set
# using the Linear Regression model
y_train_predict = lr.predict(x_train)

# predicting the output of the test set
# using the Linear Regression model
y_test_predict = lr.predict(x_test)

test_mse = mean_squared_error(y_test, y_test_predict)

# calculate root mean squared value

test_rmse = np.sqrt(test_mse)

print(round(test_rmse, 3))

0.087

# Question 18

From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the R^2 value in two D.P?

**Solution:**

In [47]:
lrr = LinearRegression()
lrr.fit(x_train[['T2']], x_train['T6'])

# calculating r_squared value
r_squared = lrr.score(x_train[['T2']], x_train['T6'])
print(round(r_squared, 2))

0.64

# Question 19

Ridge regression:

**My Answer: Reduces variance at the expense of higher bias**

# Question 20

Which of the following sentence is true about outliers in Linear Regression:

**Student Answer: Linear regression is sensitive to outliers.**